name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Define the Node.js version here

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Build Project (if applicable)
      run: npm run build  # Replace this with your actual build script if applicable

    - name: Generate and Archive Allure Reports
      if: always()  # This ensures that reports are generated even if previous steps failed
      run: |
        npm install -g allure-commandline
        allure generate output/allure-results --clean
        allure open

    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: production-artifacts
        path: output/

    - name: Archive Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report
